package:
  format-version: "1.0.0"
  name: "net_apps_pic32cx_sg41"
  version: "3.0.1"
  type: "application"
  status: "production"
  
  dependencies:
    - name: "core"
      type: "package"
      version: "v3.13.1"
    - name: "csp"
      type: "package"
      version: "v3.17.0"
    - name: "dev_packs"
      type: "package"
      version: "v3.17.0"
    - name: "crypto"
      type: "package"
      version: "v3.8.0"
    - name: "usb"
      type: "package"
      version: "v3.11.0-E2"
    - name: "wolfssl"
      type: "package"
      version: "v5.4.0"
    - name: "CMSIS-FreeRTOS"
      type: "package"
      version: "v10.5.1"
    - name: "net"
      type: "package"
      version: "v3.10.1"
