format_version: v1.0
configName: pic32cx_sg41_cult_sw
folderName: pic32cx_sg41_cult_sw
frameworkPath: C:\harmony\h3
processor: PIC32CX1025SG41128
projectName: pic32cx_sg41_cult_sw
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\PIC32CX-SG41_DFP\1.1.122\atdf\PIC32CX1025SG41128.atdf
